
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icfgruzizwwlkfsobvxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljZmdydXppend3bGtmc29idnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTM4ODUsImV4cCI6MjA2MzM4OTg4NX0.kLcdFdHk6guIHXNV2dytREfDZSeoQkvQRpaRNdD6Qu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Helper function to get the redirect URL
export const getRedirectTo = () => {
  // Use the current origin for redirects to make development and production work
  return `${window.location.origin}/auth/callback`;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});
