
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bybgaenuaxwnjgeqwifx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5YmdhZW51YXh3bmpnZXF3aWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4Nzc3NzIsImV4cCI6MjA2MjQ1Mzc3Mn0.YzbRb-rfranWgjweyrK7cIOGEskuHbLqbgQk87vqdug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    flowType: 'pkce', // Change from 'implicit' to 'pkce' for better security
    detectSessionInUrl: true,
    // The `as any` casting is necessary because of type definition mismatch
    // between current version of Supabase types and the actual API
  }
});

// This helper function adds the redirectTo option when needed
export const getRedirectTo = () => `${window.location.origin}/auth/callback`;
